version: '3'

services:
  frontend:
    image: nginx-frontend
    build: 
      context: ./frontend
      args:
        - REACT_APP_SERVICES_HOST=/services/m
    ports:
      - "8081:80"
    networks: 
      - frontend
      - backend
  
  backend:
    image: nginx-backend
    build:
      context: ./backend
    networks: 
      - backend

networks: 
  frontend:
  backend: